// This file is auto-generated — do not edit manually.
import type { IkasImage, IkasNavigationLink } from "@ikas/bp-storefront";
import type { AuthFormVariant } from "../../global-types";

export interface Props {
  variant?: AuthFormVariant;
  showGoogle?: boolean;
  showFacebook?: boolean;
  showSmsLogin?: boolean;
  image?: IkasImage | null;
  loginTitle?: string;
  registerTitle?: string;
  forgotTitle?: string;
  recoverTitle?: string;
  smsTitle?: string;
  loginText?: string;
  registerText?: string;
  forgotText?: string;
  recoverText?: string;
  smsText?: string;
  smsProfileText?: string;
  submitText?: string;
  registerSubmitText?: string;
  forgotSubmitText?: string;
  recoverSubmitText?: string;
  sendCodeText?: string;
  submittingText?: string;
  firstNameLabel?: string;
  lastNameLabel?: string;
  emailLabel?: string;
  emailPlaceholder?: string;
  passwordLabel?: string;
  newPasswordLabel?: string;
  passwordAgainLabel?: string;
  phoneLabel?: string;
  phonePlaceholder?: string;
  codeLabel?: string;
  codeSentText?: string;
  resendCodeText?: string;
  marketingConsentText?: string;
  agreementConsentText?: string;
  forgotLinkText?: string;
  socialDividerText?: string;
  googleText?: string;
  facebookText?: string;
  smsLoginText?: string;
  emailLoginText?: string;
  successText?: string;
  recoverSuccessText?: string;
  registerSuccessText?: string;
  errorText?: string;
  invalidTokenText?: string;
  switchText?: string;
  registerLinkText?: string;
  registerSwitchText?: string;
  forgotSwitchText?: string;
  loginLinkText?: string;
  newLinkText?: string;
  agreementLink?: IkasNavigationLink | null;
  marketingLink?: IkasNavigationLink | null;
  backgroundColor?: string;
  firstNamePlaceholder?: string;
  lastNamePlaceholder?: string;
  passwordPlaceholder?: string;
  codePlaceholder?: string;
}
