// This file is auto-generated — do not edit manually.
import type { IkasNavigationLink, IkasNavigationLinkList, IkasImage, IkasProductList } from "@ikas/bp-storefront";

export interface Props {
  logo?: string;
  logoAltText?: string;
  logoMonochrome?: boolean;
  showAnnouncement?: boolean;
  transparentOnHero?: boolean;
  stickyEnabled?: boolean;
  countdownTarget?: Date | string;
  announcementInterval?: number;
  announcementText?: string;
  countdownAriaLabel?: string;
  announcementPrevAriaLabel?: string;
  announcementNextAriaLabel?: string;
  searchLabel?: string;
  cartLabel?: string;
  accountLabel?: string;
  menuAriaLabel?: string;
  closeAriaLabel?: string;
  menuFeatureTitle?: string;
  menuFeatureLinkText?: string;
  loginText?: string;
  registerText?: string;
  logoutText?: string;
  menuGreetingText?: string;
  menuAccountLabel?: string;
  favoritesLabel?: string;
  localeText?: string;
  searchPlaceholder?: string;
  searchEmptyTitle?: string;
  searchResultCountText?: string;
  searchNoResultText?: string;
  searchNoResultHint?: string;
  searchAllResultsText?: string;
  cartTitleText?: string;
  cartEmptyTitle?: string;
  cartEmptyText?: string;
  cartEmptyButtonText?: string;
  drawerRecommendTitle?: string;
  couponToggleText?: string;
  couponPlaceholder?: string;
  couponButtonText?: string;
  couponErrorText?: string;
  couponAppliedText?: string;
  couponRemoveText?: string;
  cartSubtotalLabel?: string;
  cartShippingNote?: string;
  checkoutButtonText?: string;
  checkoutLoadingText?: string;
  cartViewButtonText?: string;
  editText?: string;
  removeText?: string;
  maxQuantityText?: string;
  giftText?: string;
  decreaseAriaLabel?: string;
  increaseAriaLabel?: string;
  bundlePartsText?: string;
  cookieContent?: string;
  cookieAcceptText?: string;
  announcementLink?: IkasNavigationLink | null;
  navLinks?: IkasNavigationLinkList;
  menuFeatureLink?: IkasNavigationLink | null;
  searchSuggestions?: IkasNavigationLinkList;
  menuFeatureImage?: IkasImage | null;
  drawerRecommendProducts?: IkasProductList;
  announcements?: any;
  megamenuColumns?: any;
  backgroundColor?: string;
  qbChooseOptionText?: string;
  qbAddText?: string;
  qbAddingText?: string;
  qbAddedText?: string;
  qbSoldOutText?: string;
  qbAddErrorText?: string;
  qbDetailLinkText?: string;
  qbLowStockText?: string;
  qbPrevAriaLabel?: string;
  qbNextAriaLabel?: string;
  qbFavoriteAriaLabel?: string;
  qbQuantityAriaLabel?: string;
  qbDecreaseAriaLabel?: string;
  qbIncreaseAriaLabel?: string;
  quickBuyPayWithIkas?: boolean;
  countdownDaysText?: string;
}
